// A diff line's old and new line numbers as the developer sees them beside
// it: generated by the stylesheet from the line's data, outside its text.

import type { Locator } from "@playwright/test";

// Each listed line's shown old and new numbers, empty where it has none.
export const shownLineNumbers = (lines: Locator) =>
  lines.evaluateAll((items) =>
    items.map((item) =>
      ["::before", "::after"].map(
        (side) =>
          // Shown as `"10" / ""`: the number, with nothing read aloud.
          /^"(\d*)"/.exec(getComputedStyle(item, side).content)?.[1],
      ),
    ),
  );
